[tools]
starship = "1.22.1"
opencode = "1.2.26" 
ripgrep = "15.1.0"
fd = "10.4.2"
tmux = "3.6a"
jujutsu = "0.39.0"
node = "24.14.1"
go = "latest"

# Tooling for OpenCode
"npm:@upstash/context7-mcp" = "2.1.6"
"npm:mcp-fetch-server" = "1.1.2"
# Tooling for Tmux
"go:github.com/dustinkirkland/golang-petname/cmd/petname" = "latest"
