[tools]
starship = "1.22.1"
opencode = "1.4.6" 
ripgrep = "15.1.0"
fd = "10.4.2"
tmux = "3.6a"
jujutsu = "0.39.0"
node = "24.14.1"
uv = "latest"
go = "latest"
neovim = "0.12.1"
tree-sitter = "0.26.8"
usage = "3.2.0"

# Tooling for OpenCode
"npm:@upstash/context7-mcp" = "2.1.6"
"pipx:mcp-server-fetch" = "2025.4.7"

# Tooling for Tmux
"pipx:petname" = "latest"
