[settings]
lockfile = true

[tools]
starship = "1.25.1"
opencode = "1.17.10"
ripgrep = "15.1.0"
fd = "10.4.2"
tmux = "3.6a"
jujutsu = "0.42.0"
node = "24.14.1"
uv = "latest"
go = "latest"
neovim = "0.12.3"
tree-sitter = "0.26.9"
usage = "3.5.3"
atuin = "18.16.1"
delta = "0.19.2"
rtk = "0.42.4"
github-cli = "2.95.0"
zoxide = "0.9.9"
jq = "1.8.2"
yq = "4.53.3"
yazi = "26.5.6"
"pipx:copier" = "9.16.0"
"github:tassiovirginio/try-rs" = "1.7.11"
"github:11happy/cpx" = "0.1.4"
"github:mitsuhiko/minijinja" = "2.21.0"
"github:laulauland/jj-hunk" = "0.4.1"

#"go:github.com/mitsuhiko/gh-issue-sync" = "main"
"go:github.com/mitsuhiko/gh-issue-sync/cmd/gh-issue-sync" = "main"

# Tooling for OpenCode
"npm:@upstash/context7-mcp" = "3.2.2"
"pipx:mcp-server-fetch" = "2026.6.4"
"npm:tavily-mcp" = "0.2.20"
"npm:exa-mcp-server" = "3.2.1"

# Tooling for Tmux
"pipx:petname" = "latest"
