set -g default-shell /usr/bin/zsh

# General settings
set -g mouse on
set -g status-keys vi
set -g mode-keys vi

set -g set-clipboard on

set-option -sg escape-time 10
set-option -g focus-events on

# Theme configuration
set -g @catppuccin_flavor 'macchiato'
set -g status-position top
set -g @catppuccin_window_status_style "none"

run '~/.config/tmux/plugins/catppuccin/catppuccin.tmux'

# Status bar
set -g window-status-format ""
set -g window-status-current-format ""

set -g status-left-length 100
set -g status-right-length 100
set -g status-left "sklein-devbox: #(echo $SKLEIN_DEVBOX_NAME)"
set -g status-right ""

# Window and pane management
bind-key c new-window -c "#{pane_current_path}" -n ""
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

bind-key Up    select-pane -U
bind-key Down  select-pane -D
bind-key Left  select-pane -L
bind-key Right select-pane -R

# Copy mode (vi-like)
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "tmux load-buffer -w -"