set -g @catppuccin_flavor 'macchiato'
set -g status-position top
set -g @catppuccin_window_status_style "none"

run '~/.config/tmux/plugins/catppuccin/catppuccin.tmux'

set -g window-status-format ""
set -g window-status-current-format ""

set -g status-left-length 100
set -g status-right-length 100
set -g status-left "sklein-devbox: #(echo $SKLEIN_DEVBOX_NAME)"
set -g status-right ""