set -g default-shell /usr/bin/zsh

set-hook -g after-new-session "run-shell 'sleep 0.1 && bash ~/.config/tmux/scripts/init-window.sh'"

# General settings
set -g mouse on
set -g status-keys vi
set -g mode-keys vi

set -g set-clipboard on

set-option -sg escape-time 10
set-option -g focus-events on

set -g automatic-rename off

# Theme configuration
set -g @catppuccin_flavor 'macchiato'
set -g status-position top
set -g @catppuccin_window_status_style "none"

run '~/.config/tmux/plugins/catppuccin/catppuccin.tmux'

# Status bar
set -g window-status-format ""
set -g window-status-current-format ""

set -g status-left-length 100
set -g status-right-length 100
set -g status-left "🧰 #(echo $SKLEIN_DEVBOX_NAME) 󰓩 #{window_name} ❯ #(~/.config/tmux/scripts/current-path.sh #{pane_current_path})"
set -g status-right ""

# Window and pane management
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

bind-key w display-popup -E -w 95% -h 95% \
  "bash ~/.config/tmux/scripts/choose-window.sh"

bind-key Up    select-pane -U
bind-key Down  select-pane -D
bind-key Left  select-pane -L
bind-key Right select-pane -R

# Copy mode (vi-like)
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "tmux load-buffer -w -"

# Update status bar on pane change
set-hook -g after-select-pane "refresh-client -S"

bind-key c run-shell "bash ~/.config/tmux/scripts/new-window.sh"
bind-key r display-popup -E -w 50 -h 5 \
  "bash ~/.config/tmux/scripts/rename-window.sh"
