#:schema https://starship.rs/config-schema.json
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
${custom.jj}\
$golang\
$nodejs\
$python\
$terraform\
$memory_usage\
$mise\
$shell\
$character
"""

[custom.jj]
symbol = ""
style = "bold green"
format = "[$symbol$output]($style) "
when = "jj-starship detect"
shell = ["jj-starship", "--no-color", "--no-symbol", "--no-jj-prefix", "--no-git-prefix"]

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
